service: Provisioning

provider:
  name: aws
  runtime: nodejs6.10
  stackName: Provisioning
  memorySize: 512                                               # optional, in MB, default is 1024
  timeout: 30                                                   # optional, in seconds, default is 6
  role: arn:aws:iam::084009911244:role/service-role/Admintest
  endpointType: EDGE
  deploymentBucket:
    name: vishaldxc-${opt:region, self:provider.region}

functions:
  createStack:
    handler: createstack.handler                             # The handler property points to the file and module containing the code you want to run in your function.
    name: createStack
    # package:
    #   include:
    #     - node_modules/aws-sdk
    events:
      - http: 
          path: dxc/createStack/r1/V1
          method: post
          authorizer: aws_iam
  describeStack:
    handler: describestack.handler
    name: describeStack
    # package:
    #   include:
    #     - node_modules/aws-sdk
    events:
      - http:       
          path: dxc/describeStack/r1/V1
          method: get
          authorizer: aws_iam
